#!/usr/bin/env bash
#Bash script that installs nginx on my Web-01 server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx restart

sudo rm /var/www/html/*.html
sudo echo "Hello World\n" | sudo tee /var/www/html/index.html