#!/usr/bin/env bash
# installs ngix to server ad well as seting custom headers
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html

yt="https://www.youtube.com/watch?v=QH2-TGUlwu4"
old_loc="^\tlocation / {"
new_loc="\tlocation /redirect_me {\n\t\treturn 301 \$scheme:$yt;\n\t}\n\n\tlocation / {\n\t\tadd_header X-Served-By '$HOSTNAME';"
sudo sed -i "s|$old_loc|$new_loc|" /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_loc="\terror_page 404 /404.html;\n\n\tlocation / {"
sudo sed -i "s|$old_loc|$new_loc|" /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart