#!/usr/bin/env bash
# installs ngix to server ad well as seting custom headers
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo service nginx start
string="server_name alliecat.tech;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\
\?v=QH2-TGUlwu4;\n\t}"
err404="\terror_page 404 \/error404.html;\n\tlocation = \/error404.html {\n\t\tinternal;\n\t}"
both="${string}\n${err404}"
sudo sed -i "s/server_name _;/$both/" /etc/nginx/sites-enabled/default
tf="add_header X-Served-By $(hostname);"
sudo sed -i "62 a $tf" /etc/nginx/nginx.conf
sudo service nginx restart